trycourier/website

src/components/layout.tsx
```html
<script>
window.savvy=window.savvy||[],savvy.load=function(d,b){window.savvy.orgId=d,window.savvy.config=b=b||{};var e=b.forceSSL||'https:'===document.location.protocol,a=document.createElement('script');a.type='text/javascript',a.async=!0,a.src=(e?'https://savvy-prod.firebaseapp.com/js/generate?script=website_visitors&org_id=':'http://savvy-prod.firebaseapp.com/js/generate?script=website_visitors&org_id=')+d,console.log('a.src',a.src);var c=document.getElementsByTagName('script')[0];c.parentNode.insertBefore(a,c);},savvy.load('cju66UfGwvk8uiyVbwFf');
</script>
```
=> add Savvy script

bin/sentry-release.sh
=> upload sourcemaps

src/data/pricing.ts
=> update pricing to match Stripe

src/components/footer.tsx
> Adds "Careers" link to the Lever page as an external link in the footer.
- [ x ] New feature (non-breaking change that adds functionality)
> Fix [#1]()
=> [C-490] add careers link

src/components/footer.tsx, src/data/terms.tsx, src/pages/terms.tsx
=> terms of service

package.json, yarn.lock
To fix:
https://github.com/trycourier/website/network/alert/yarn.lock/graphql-playground-html/open
=> upgrade Gatsby

content/subprocessors.yaml, package.json, src/components/footer.tsx, src/components/subprocessors.tsx, src/pages/subprocessors.tsx, yarn.lock
=> list subprocessors on website for GDPR

gatsby-config.js, gatsby-node.js, package.json, src/components/community/articles.tsx, src/pages/blog/authors.tsx, src/pages/blog/index.tsx, src/pages/blog/tags.tsx, src/pages/community.tsx, src/templates/author.tsx, src/templates/blog-post.tsx, src/templates/tag.tsx, yarn.lock
There's still a lot of cleanup that can be done. The blog is functioning as it was with markdown. There were some extra things I had to do to make all the parts of the blog work that previously weren't.
> Fix [#1]()
=> Migrated from using markdown to using Contentful models

gatsby-config.js, gatsby-node.js, src/components/community/tag.tsx, src/components/layout.tsx, src/pages/blog/index.tsx, src/pages/blog/tags.tsx, src/pages/community.tsx, src/templates/author.tsx, src/templates/blog-post.tsx, src/templates/tag.tsx
Blog tweaks before going live.
> Fix [#1]()
=> Blog Tweaks

src/components/community/articles.tsx, src/components/community/cta-link.tsx, src/templates/blog-post.tsx, src/templates/tag.tsx
=> Updated blog card font and added CTA link button

src/components/community/cta-link.tsx, src/components/navigation.tsx, src/templates/blog-post.tsx
=> add intercom button, fix blog post footer layout

package.json, src/components/community/articles.tsx, src/pages/blog/index.tsx, src/pages/community.tsx, src/templates/author.tsx, src/templates/blog-post.tsx, src/templates/tag.tsx, yarn.lock
Switched avatars and thumbnails to use gatsby-image. Set og:image to headerImage.
> Fix [#1]()
=> Blog Images updates

src/components/syntax-highlighter/index.tsx
Added ability to use a CSS code snippet.
> Fix [#1]()
=> Added CSS as an option for Code Snippet

src/components/home/one-api-call.tsx
Fix for bad link reported on twitter.
https://twitter.com/guillermocastro/status/1299093731866533889?s=21
> Fix [#1]()
=> Fixed reported docs link

src/pages/signal.tsx
=> remove raffle

src/pages/signal.tsx
=> Update Streaming Links on Signal Page

src/links.ts, src/pages/privacy.tsx
resolves https://linear.app/trycourier/issue/C-1726/fix-more-website-trycourierapp-links
additional changes supporting the `app.courier.com` migration
=> few more places we still have `https://www.trycourier.app`

src/pages/privacy.tsx
=> Correct legal entity name

content/subprocessors.yaml
Add LaunchDarkly as a subprocessor
=> Add LaunchDarkly as a subprocessor

src/pages/privacy.tsx
=> Update privacy policy

netlify.toml
https://linear.app/trycourier/issue/C-2135/marketing-website-set-up-url-redirect
=> Marketing website: Set up URL redirect for SEDaily

netlify.toml
-Report Only Content Security Policy
> Fix [#1]()
=> Add CSP to header

netlify.toml
- line wrapping fix on CSP
> Fix [#1]()
=> [C-2328] HackerOne add CSP

netlify.toml
Added a redirect for courier.com/bitcamp to go to a utm coded sign up.
> Fix [#1]()
=> Added sign up redirect for bitcamp

netlify.toml
Added codestory redirect for Micah
=> Added redirect for codestory

src/components/seo.tsx
[C-2823] Add G2 tracking
https://linear.app/trycourier/issue/C-2823/g2-tracking-tag
=> [C-2823] Add G2 tracking

netlify.toml
Added sign up redirect for TOHacks
=> Added sign up redirect for TOHacks

netlify.toml
=> fix multiple redirects take 2

netlify.toml
=> remove another unnecessary redirect

netlify.toml
=> fix another redirect

src/components/pages/providers/data.tsx
=> fix Plivo typo

netlify.toml
=> Move CSP in to blocking mode

_redirects
=> fix favicon redirect

src/components/pages/blog/common/FeaturedBlock/MainArticle.tsx, src/components/pages/blog/tag/FeaturedBlock/index.tsx, src/scripts/GetAllBlogs.tsx, src/scripts/GetBlogsForTag.tsx, src/scripts/GetBlogsHomeFeed.tsx
This PR fixes consistency issues with blog feed sort order so that it's showing latest > oldest posts.
=> Fix blog feed sort order
